### ISSUE TITLE
intro__text

### ISSUE THREAD

**Issue by demidovakatya** [pvolyntsev/web-mastery-skills#1]
Предлагаю сделать intro__text более читаемым. 
Например, так [(скриншот)](https://cloud.githubusercontent.com/assets/5788652/10303350/e78dc876-6c1b-11e5-9100-26764d76ffa6.png). 
CSS:

```
.intro__text { font-weight:400; text-transform:none; font-size:16px; }
```

**Comment by pvolyntsev** [comment]
Спасибо, хорошее замечание. Не буду обычный текст в верхний регистр преобразовывать.
А ещё есть прототип новой версии опросника http://web-mastery-gauge.ru/
Всё никак не решусь его сделать

**Comment by demidovakatya** [comment]
У меня на [этой](http://web-mastery-gauge.ru/?page=intro) странице [такой первый экран](https://www.dropbox.com/s/9rh8sbnq7lwgaxs/Screenshot%202015-10-06%2014.49.37.png). 
Думала, это тайна пропавшего скроллинга — ан нет, там и скроллить некуда :) 

Это мелочи, впрочем. Интересный проект, мне нравится и идея, и реализация.

**Comment by demidovakatya** [comment]
Ок, если я issues позавожу?

**Comment by pvolyntsev** [comment]
> У меня на этой странице такой первый экран. 
> Думала, это тайна пропавшего скроллинга — ан нет, там и скроллить некуда :)

Ага, не респонсив :(

**Comment by pvolyntsev** [comment]
> Ок, если я issues позавожу?
> Да, конечно :)

**Comment by pvolyntsev** [comment]
Хочешь поучаствовать в создании следующей версии опросника? Напиши мне, контакты на http://copist.ru/about

**Comment by demidovakatya** [comment]
написала на почту, если что

**Comment by pvolyntsev** [comment]
Resolved and released
