### ISSUE TITLE
Intro page doesn't fit the browser

### ISSUE THREAD

**Issue by demidovakatya** [pvolyntsev/web-mastery-skills#2]
Съезжает [Введение](http://web-mastery-gauge.ru/?page=intro).

Скриншот до нижнего края браузера:
![Скриншот](https://cloud.githubusercontent.com/assets/5788652/10308497/ba48c3b6-6c3e-11e5-8431-bf5263371755.png)

Скролла нет.
Разрешение экрана: 1440*900

**Comment by pvolyntsev** [comment]
Исправил в новой версии. Готовится к публикации.
